c++:
  cxx_clang_path: /usr/bin/clang++
c:
  c_clang_path: /usr/bin/clang

test_function_signature: "(?:(?!.*~)(?!.*Failure)).*TestBodyEv"
assertion_function_signature: ".*?AssertionResult.*?"

project_path: /mnt/c/Users/larsv/Documents/GitHub/Goal-Oriented-Mutation-Testing/example-cpp

base_language: c++
build_target: linked

max_depth: 1

debug: False
graph: True