test_function_signature: "(?:(?!.*~)(?!.*Failure)).*TestBodyEv$"
assertion_function_signature: '.*?AssertionResult.*?|(?!.*?AssertHelper.*).*?testing8internal.*?|.*?class.testing.*?'
exclusion_filter: '@_ZNKSt7.*?|@_ZN6stride4util1.*?|@_ZNSt7|@_ZN9__gnu_cxx17|@_ZNSt10.*?'

project_path: /mnt/c/Users/larsv/Desktop/Goal-Oriented-Mutation-Testing/exampleProjects/stride

max_depth: 1

graph: False